---
title: "HTTK QSPRs: Text for Manuscript"
author: "John Wambaugh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HTTK QSPRs: Text for Manuscript}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir= "C:/Users/jwambaug/git/CompTox-ExpoCast-HTTKQSPRs/")
```

```{r clear_memory, eval=TRUE}
rm(list=ls()) 
```

```{r load_libraries, eval=TRUE}
library(httk)
```

```{r load_data, eval= TRUE}
load("data/interspecies.RData")
load("data/Cvt-chems.RData")
load("data/Cvt-data.RData")
load("data/cvT-chems-nona.RData")
load("data/fittable.RData")
load("data/level3-tables.RData")
load("data/level2stats.RData")
load("data/httk-goodchems.RData")
load("data/chemicallists.RData")
load("data/benchmarkstats.RData")
  # Can't work with NA's:
  level3tab <- level3tab[!names(level3tab) %in% c("HTPBTK-InVitro-AltClear","HTPBTK-InVitro-Rat")]
```

# Abstract
```{r textforabstract}
cat(paste0("We estimate that using rat in vivo data to evaluate QSPR models trained on human in vitro measured data might inflate error estimates by as much as root mean squared log10 (RMSLE) ",
  signif(max(rathum.table["Non-Restrictive",]), 1),
  ".\n"))
cat(paste0("We estimate that AUC can be predicted by HTTK with RMSLE ",
  signif(as.numeric(strsplit(AUC.stats.table["RMSLE In Vitro","HTPBTK-InVitro"]," ")[[1]][1]),1),
  " for in vitro measurements and ",
  signif(min(sapply(AUC.stats.table["RMSLE In Vitro",4:8],
                    function(x) as.numeric(strsplit(x," ")[[1]][1]))
                    ),1),
  "-",
  signif(max(sapply(AUC.stats.table["RMSLE In Vitro",4:8],
                    function(x) as.numeric(strsplit(x," ")[[1]][1]))
                    ),1),
  " for QSPR models.\n"))
```
# Highlights
```{r textforhighlights}
cat(paste0("Using rat in vivo data to evaluate human HTTK may have increased the error by as much as RMSLE ",
  signif(max(rathum.table["Non-Restrictive",]), 1),
  ".\n"))    
cat(paste0("A physiologically based toxicokinetic model using QSPR model predictions performed similarly to when in vitro values are used (RMSLE ~",
  signif(as.numeric(strsplit(rmsle.stats.table["In Vitro","HTPBTK-InVitro"]," ")[[1]][1]),1),
  ").\n"))
```
# Results

## Evaluation Chemicals and Predictions
```{r text_for_eval_chems_and_preds}
cat(paste0("There were ",
           length(unique(subset(fittable,is.na(Vdist))$DTXSID)),
           " chemicals where we could not estimate Vd.\n"))
cat(paste0("There were ",
           length(unique(subset(fittable,is.na(Fgutabs))$DTXSID)),
           " chemicals where we could not estimate Fgutabs.\n"))
cat(paste0("Among the ",
           length(unique(fittable$DTXSID)),
           " remaining evaluation chemicals, ",
           length(unique(subset(fittable,Species=="rat")$DTXSID)),
           " had data in rat and ",
           length(unique(subset(fittable,Species=="human")$DTXSID)),
           " in human.\n")) 

cat(paste("The three chemicals with the shortest half-lives in rat were",
      paste(CvT.chems[order(CvT.chems$Thalf.fit)[1:3],]$PREFERRED_NAME,collapse=", "),
      "-- mean of",
      signif(mean(CvT.chems[order(CvT.chems$Thalf.fit)[1:3],"Thalf.fit"]),1),
      "hours.\n"))

cat(paste("The three chemicals with longest half-lives in rat were",
      paste(CvT.chems[order(CvT.chems$Thalf.fit,decreasing=TRUE)[1:3],]$PREFERRED_NAME,collapse=", "),
      "-- mean of",
      signif(mean(CvT.chems[order(CvT.chems$Thalf.fit,decreasing=TRUE)[1:3],"Thalf.fit"]),1),
      "hours.\n"))

pharma <- read.csv("ccd_data/Chemical List ZINC15PHARMA-2024-09-09.csv")
cat(paste(sum(CvT.chems$CASRN%in%pharma$CASRN),
      "of the chemicals with in vitro HTTK data and in vivo concentration vs. time data were pharmaceuticals.\n"))

```
```{r describe_chemicals, eval=TRUE}
pharma <- read.csv("ccd_data/Chemical List ZINC15PHARMA-2024-09-09.csv")
pest.active<- read.csv("ccd_data/Chemical List EPAPCS-2024-12-09.csv")
PFAS <- read.csv("ccd_data/Chemical List PFAS8a7v3-2024-12-09.csv")
ToxCast <- read.csv("ccd_data/Chemical List ToxCast_invitroDB_v4_1-2024-12-09.csv")
TSCA <- read.csv("ccd_data/Chemical List TSCA_ACTIVE_NCTI_0224-2024-12-09.csv")
consumer <- read.csv("ccd_data/Chemical List EPACONS-2024-12-09.csv")

cat(paste("Among the",
          dim(CvT.chems)[1],
          "evaluation chemicals,",
          length(unique(subset(CvT.data, DTXSID %in% CvT.chems$DTXSID & Species=="rat")$DTXSID)),
          "had data in rat and",
          length(unique(subset(CvT.data, DTXSID %in% CvT.chems$DTXSID & Species=="human")$DTXSID)),
          "in human.\n"))

cat(paste("The",
          length(unique(CvT.chems$DTXSID)),
          "chemicals included (according to lists accessed 12/9/24)",
          length(unique(subset(CvT.chems, CASRN %in% pharma$CASRN)$CASRN)),
          "pharmaceuticals.\n"))

cat(paste("Additionally, the evaluation chemicals included:",
            dim(subset(CvT.chems, CASRN %in% TSCA$CASRN))[1],
          "from the non-confidential Toxic Substances Control Act (TSCA) active inventory (https://comptox.epa.gov/dashboard/chemical-lists/TSCA_ACTIVE_NCTI_0224),",
            dim(subset(CvT.chems, CASRN %in% pest.active$CASRN))[1],
          "pesticide active ingredients (https://comptox.epa.gov/dashboard/chemical-lists/EPAPCS),",
          dim(subset(CvT.chems, CASRN %in% consumer$CASRN))[1],
          "that are found in consumer products (https://comptox.epa.gov/dashboard/chemical-lists/EPACONS),",
          dim(subset(CvT.chems, CASRN %in% PFAS$CASRN))[1],
          "per- and poly-fluoroalkyl substances (PFAS) (https://comptox.epa.gov/dashboard/chemical-lists/PFAS8a7v3), and",
          dim(subset(CvT.chems, CASRN %in% ToxCast$CASRN))[1],
          "that are part of the ToxCast screening program (https://comptox.epa.gov/dashboard/chemical-lists/ToxCast_invitroDB_v4_1).\n"))
```

## Interspecies concondrdance
```{r textforpaper}
cat(paste("Only",
          dim(subset(CvT.chems,DTXSID%in%common_chems_all))[1],
          "evaluation chemicals had both human and rat in vitro HTTK data.\n"))
cat(paste("However, there are",
      length(unique(common_chems)),
      "chemicals with in vitro measured fup and Clint for both human and rat.\n"))

cat(paste0("The rat-human differences were RMSLE ",
           signif(fup_rmsle,2),
           " for fup and ",
           signif(clint_rmsle,2),
           " for Clint.\n"))

cat(paste0("As shown in Figure 2, RMSLE for Css was ",
           signif(rathum.table["Non-Restrictive","Css"], 2),
           ", RMSLE for Cmax was ",
           signif(rathum.table["Non-Restrictive","Cmax"], 2),
           ", and for AUC RMSLE was ",
           signif(rathum.table["Non-Restrictive","AUC"], 2),
           ".\n"))

cat(paste0("Errors were slightly smaller for the ",
           dim(subset(CvT.chems,DTXSID%in%common_chems_all))[1],
           " chemicals with CvT data used in subsequent evaluations – RMSLE for Css was ",
           signif(rathum.table["Non-Restrictive CvT","Css"], 2),
           ", Cmax was ",
           signif(rathum.table["Non-Restrictive CvT","Cmax"], 2),
           ", and AUC was ",
           signif(rathum.table["Non-Restrictive CvT","AUC"], 2),
           ".\n")) 
```
## Performance Benchmarks

```{r text_for_performance_benchmarks}
good.chems <- get_cheminfo(info="dtxsid",
                           model="gas_pbtk",
                           class.exclude=FALSE,
                           suppress.messages=TRUE)
good.cvt.chems <- CvT.chems$DTXSID[CvT.chems$DTXSID %in% good.chems]
invitro.clint <- subset(chem.physical_and_invitro.data,
                        !is.na(Human.Clint))$DTXSID
invitro.fup <- subset(chem.physical_and_invitro.data,
                      !is.na(Human.Funbound.plasma))$DTXSID

cat(paste0("There were ",
           sum(CvT.chems$DTXSID%in%invitro.clint),
           " evaluation chemicals with in vitro measured Clint and ",
           sum(CvT.chems$DTXSID%in%invitro.fup),
           " chemicals with in vitro measured fup, for a total of ",
           sum(CvT.chems$DTXSID%in%invitro.fup | CvT.chems$DTXSID%in%invitro.clint),
           " unique chemicals. However, since there were only ",
           dim(subset(get_cheminfo(info=c("DTXSID","Funbound.plasma"),
                                   model="gas_pbtk",
                                   class.exclude=FALSE,
                                   suppress.messages=TRUE),
       DTXSID %in% CvT.chems$DTXSID & Human.Funbound.plasma>0))[1],
           " chemicals where fup > 0, which is required for the HT-PBTK model, ",
           "in vitro-based predictions could only be evaluated for this set of ",
           sum(CvT.chems$DTXSID%in%good.chems),
           " chemicals.\n")) 

NUM.CHEMS <- length(good.cvt.chems)
cat(paste(
  "It appears clear from the median error for HT-PBTK simulations that the ",
  "majority of chemicals in this set are non-restrictive (RMSLE ",
  bench.table["CvT RMSLE",
              paste0("In Vitro Non-Restrictive (",
              NUM.CHEMS,
              ")")],
  ") rather than restrictive (",
  bench.table["CvT RMSLE",paste0("In Vitro Restrictive (",
              NUM.CHEMS,
              ")")],
  ").\n",
  sep=""))


cat(paste0("Note that the performance for y-randomization with non-restrictive",
           " clearance (",
                      bench.table["CvT RMSLE",
                     paste0("Y-Randomized (",
                     NUM.CHEMS,
                     ")")],
           ") in Table 5 is not directly comparable to the performance of ",
           "restrictive clearance. Both can be compared to the performance of ",
           "non-restrictive clearance but are not meaningfully compared to ",
           "each other since the y-randomization was only conducted for the ",
           "for the non-restrictive case.",
           " The error of y-randomized restrictive simulations would be larger.\n"))

AUC.rmsle.nr <- bench.table["AUC RMSLE",
                     paste0("In Vitro Non-Restrictive (",
                     NUM.CHEMS,
                     ")")]
AUC.rmsle.yrand <- bench.table["AUC RMSLE",
                     paste0("Y-Randomized (",
                     NUM.CHEMS,
                     ")")] 
AUC.yrand.change <- signif(AUC.rmsle.yrand/AUC.rmsle.nr, 2) 
cat(paste(
  "For example, the difference in prediction error for AUC is a factor of ",
  AUC.yrand.change,
  "-fold (or ",
  signif(10^(AUC.yrand.change),2),
  " times) between the appropriate in vitro value (",
  bench.table["AUC RMSLE",
              paste0("In Vitro Non-Restrictive (",
              NUM.CHEMS,
              ")")],
  ") and the y-randomized value (",
  bench.table["AUC RMSLE",
              paste0("Y-Randomized (",
              NUM.CHEMS,
              ")")],
  ").\n",
  sep=""))

early.rmsle.nr <- bench.table["Early CvT RMSLE",
                     paste0("In Vitro Non-Restrictive (",
                     NUM.CHEMS,
                     ")")]
early.rmsle.yrand <- bench.table["Early CvT RMSLE",
                     paste0("Y-Randomized (",
                     NUM.CHEMS,
                     ")")] 
early.yrand.change <- signif(early.rmsle.yrand/early.rmsle.nr, 2) 

cat(paste(
  "In contrast, there is little difference for early CvT data -- a factor of ",
  early.yrand.change,
  "-fold between the appropriate in vitro value (",
  early.rmsle.nr,
  ") and the y-randomized value (",
  early.rmsle.yrand,
  ").\n",
  sep=""))

```
## QSPR model predictions
```{r text_for_QSPR_model_predictions, eval = TRUE}
if (length(intersect.chems)==0) 
{
  cat(paste0("Unfortunately, there were no ",
    "chemicals with predictions from every QSPR.\n"))
} else {
  cat(paste0("There were ",
                length(intersect.chems)),
         "chemicals with predictions from every QSPR -- we denote this subset ",
         "as \"intersection\".\n")
}
```

## Level 1 Analysis
```{r text_for_level_1_analysis}
cat(paste("Evaluation data for Clint for",
      sum(sapply(invitro$Human.Clint,function(x) !is.na(x))),
      "chemicals and fup for",
      sum(sapply(invitro$Human.Funbound.plasma,function(x) !is.na(x))),
      ".\n"
      ))

```

### Ensemble Model
```{r text_for_ensemble_model}
cat(paste0("However, there were ",
           sum(!is.na(CvT.chems.nona$Human.Clint.Max) & !is.na(CvT.chems.nona$Human.Fup.Mean)),
           " chemicals where at least one of the QSPR models could make a prediction.\n"
           ))
```
## Level 2 Analysis
```{r text_for_level_2_analysis}
cat(paste0("The QSPR models perform roughly equally, with RMSLE generally ",
           "ranging between ",
           1.1,
           "and ",
           1.3,
           "in Table 7.\n"))

cat(paste0("In Table 8 we compare the RMSLE, AAFE, and AFE. AFE indicates ",
           "bias, with tendency to over-estimate – the AFE of ",
           0.69,
           "for predictions based on measured in vitro parameters corresponds ",
           "to an average over-estimation of ",
           4.9,
           "-fold. The empirical fits to the in vivo data slightly "
           "underestimated the observations.\n"))

cat(paste0("Based on the full time series, the ensemble QSPR model ",
           "predictions, using the most rapid predicted clearance, shows a ",
           "slightly reduced average RMSLE of ",
           1.1,
           " compared to the in vitro measured data; however, the OPERA QSPR ",
           "shows an even smaller average RMSLE of 1.0. When considering only ",
           "the later timepoints, the ensemble QSPR and OPERA QSPR have the ",
           "lowest average RMSLE values (",
           1.2,
           "),\n"))


```

## Level 3 Analysis
```{r text_for_level_3_analysis}
In vitro measured Clint and fup data predict AUC with an RMSLE of 1.3, while the QSPR models range from RMSLE 1.1 to 1.4. The ensemble and OPERA QSPR model predictions have the lowest RMSLE of 1.1, but the ensemble QSPR provides predictions for more chemicals. 

From the AFE in Table 8, we see that there is a tendency to over-predict concentrations. All 


Most of the QSPR models and the in vitro measured Clint and fup data were unsuccessful for predicting t½, with RMSLE indicating errors between 1.5 and 1.8 (32- to 63-fold). The QSPR models that were trained specifically to t½, data (rather than in vitro measured Clint and fup) produce better predictions except when compared with the ensemble QSPR model. 

```

# Discussion
```{r text_for_discussion}
Because the CvT data are also limited (81 chemicals), we have included training set chemicals in the Level 2 and 3 evaluations.

. Comparison of the HT-PBTK predictions made with rat in vitro TK parameters against predictions made with human in vitro TK parameters indicated that species differences could inflate RMSLE by as much as 0.9 (Figure 9)

TK model parameters estimated empirically from the full time course of in vivo data had mean RMSLE of 0.30 (AAFE 1.7) across all chemicals, while HT-PBTK model simulations based on in vitro Clint and fup measurements had a mean RMSLE of 1.2 (AAFE 38). 
Across the full time course, both the in vitro measured data and QSPR model predictions only performed slightly better than the y-randomized predictions (RMSLE 1.3, AAFE 78).

For the elimination phase, the HT-PBTK models parameterized using in vitro measurements had a mean RMSLE of 1.4, while the RMSLE values for HT-PBTK models parameterized using individual QSPR model predictions ranged from 1.2 – 1.4. In comparison, the HT-PBTK models parameterized using y-randomized values had a mean RMSLE of 1.5.

An ensemble prediction using the maximum clearance predicted across all QSPR models had an RMSLE of 1.1 and 1.2 for the full time-course and elimination phase, respectively. 

cat(paste0("However, the AFE suggests that the non-restrictive assumption is ",
           "still slightly conservative from a human health risk assessment ",
           "perspective (",
           0.69,
           "restrictive versus ",
           0.09,
           "non-restrictive; Suppl Table 7).\n"))




reset_httk()
tot.zero <- sum(sapply(get_cheminfo(info="Clint",
                                    median.only = TRUE,
                                    class.exclude = FALSE,
                                    suppress.messages = TRUE),
                       function(x) 0%in%x))
tot.clint <- sum(sapply(get_cheminfo(info="Clint",
                                     median.only = TRUE,
                                     class.exclude = FALSE,
                                     suppress.messages=TRUE),
                        function(x) !is.na(x)))
cat(paste(sum(invitro$Human.Clint%in% 0),
          "out of",
          sum(!is.na(invitro$Human.Clint)),
          "chemicals with in vitro HTTK Clint measured data have no observed clearance (that is, they are metabolically stable) compared with",
          tot.zero,
          "out of",
          tot.clint,
          "measured Clint values (",
          signif(tot.zero/tot.clint*100,2),
          "percent) in the httk data set as whole.\n"
          ))
cat("\n")

Here we observe that empirical one- or two-compartment fits to the CvT data can predicted Cmax with RMSLE 0.7 (5-fold) and AUC with RMSLE 0.62 (4-fold) (Table 9), (Padilla Mercado et al. 2025)). 

As summarized in Table 9, here we found that Cmax could be predicted with an RMSLE of 0.82 with in vitro measured data and an RMSLE of 0.81 with the ensemble QSPR model. AUC could be predicted with RMSLE of 1.3 using in vitro measured data and 1.1 using the ensemble QSPR model. 

For AUC predicted with in vitro parameters, we observe an RMSLE of 1.1 for pharmaceutical compounds (13-fold) and 1.5 (32-fold) for non-pharmaceuticals

Using chemicals with Clint and fup measured both in human and rat, we found that predictions of Cmax had mean RMSLE of 0.24 across chemicals when human data were used instead of rat. AUC had RMSLE of 0.31. 

. The observed error for AUC was 1.3 (in Table 9), while the interspecies error was estimated to be 0.307. 

For AUC, optimized empirical TK model fits to the in vivo data indicated an RMSLE of 0.16 while the HT-PBTK model parameterized using in vitro values for random (incorrect) chemicals had an AUC RMSLE of 1.8. 

Using chemical-specific in vitro measured data in the HT-PBTK model simulated the AUC with an RMSLE 1.3, while HT-PBTK model simulations using QSPR model predictions ranged in RMSLE values from 1.1-1.4. HT-PBTK models simulations base on the ensemble QSAR model predictions, using the maximum clearance predicted across all QSPR models, predicted the AUC with an RMSLE of 1.1 – this is better than using the in vitro measured data for the evaluation chemicals. Using the ensemble QSPR model parameter predictions, the total clearance CLtot RMSLE is 1.4. For Cmax, the empirical TK model fits had an RMSLE 0.21, while HT-PBTK models parameterized using Clint and fup for random chemicals had an RMSLE of 0.88. Note that physico-chemical properties, which largely determine Cmax, were not randomized, which is why the sensitivity analysis in Figure 9 shows Cmax is insensitive to Clint and fup. HT-PBTK model simulations using in vitro measured data had an RMSLE of 0.84 for Cmax QSPR models, while the HT-PBTK models parameterized using QSPR model predictions showed RMSLE values for Cmax ranging from 0.72-0.89, with the ensemble QSPR model predictions being 0.77. Overall, predictions of Vd had RMSLE ranging between 0.81-1.1, with the random model yielding 1.0. Here, we have assumed that Fbio only depends on first-pass metabolism, as informed by Clint. This bioavailability assumption does not appear to explain the observed discrepancies with in vivo data. The uncertainty analysis (Figure 9) confirmed that improving HTTK estimates of the elimination phase would be most likely to enhance prediction accuracy. Two of the QSPR models predicted t1/2, so a QSPR prediction for Vd was needed to compare the predictions to in vivo data. However, as we see in Figure 9, Vd is predicted relatively accurately from physico-chemical properties. For a set of 1352 pharmaceuticals Bouarar et al. (2019) found that they could directly predict Vd (RMSE 0.208), CLtot (RMSE 0.103), and t½ (RMSE 0.154).


```